[global]
trackers_list_time =
trackers_list_source =
trackers_auto_update = true
tracker_source_keys = ["ngosang", "xiu2"]
tracker_custom_sources = []
quit_with_aria2 = false
update_interval = 2000
rpc_port_changeable = false
language = system
legacy_download_path_handled = false
tray_icon_style = colorful
show_aria2_status = true
theme_mode = system
accent_color = #1c71d8
user_agent_presets = []
