"""Centralized runtime translations for Ashore."""

from PyQt6.QtCore import QLocale

LANGUAGES = {
    'zh_CN': '简体中文',
    'zh_TW': '繁體中文',
    'en': 'English',
}


def systemLanguage(localeName=None):
    """Return the supported Ashore language closest to the system UI language."""
    if localeName is None:
        locale = QLocale.system()
        uiLanguages = locale.uiLanguages()
        localeName = uiLanguages[0] if uiLanguages else locale.name()
    name = str(localeName).replace('-', '_')
    if name in LANGUAGES:
        return name

    parts = name.split('_')
    language = parts[0].lower()
    localeParts = {part.upper() for part in parts[1:]}

    if language == 'zh':
        if localeParts & {'HANT', 'TW', 'HK', 'MO'}:
            return 'zh_TW'
        return 'zh_CN'
    if language == 'en':
        return 'en'
    return 'en'


def resolveLanguage(configured=None, localeName=None):
    """Resolve a configured language, using the system language for defaults."""
    if configured in LANGUAGES:
        return configured
    if configured in (None, '', 'system'):
        return systemLanguage(localeName)
    return 'en'

TEXT = {
    'zh_CN': {
        'new': '新建下载', 'saveSession': '保存会话', 'restart': '重启 Aria2',
        'quit': '退出程序', 'startAll': '开始全部', 'pauseAll': '暂停全部',
        'show': '显示窗口', 'hide': '关闭窗口', 'about': '关于 Ashore',
        'showMain': '显示主窗口', 'trayQuit': '退出', 'exiting': '正在退出…',
        'downloading': '下载中', 'downloaded': '已完成', 'settings': '设置',
        'more': '更多',
        'startupLoadingConfig': '正在读取配置',
        'startupCheckingInstance': '正在检查运行实例',
        'startupCheckingAria2': '正在检查 aria2',
        'startupAria2Connected': 'aria2 已连接',
        'startupPreparingWindow': '正在准备主界面',
        'startupSyncingDownloads': '正在同步下载任务',
        'startupShowingWindow': '正在显示主界面',
        'startupRecheckingAria2': '正在重新检查 aria2',
        'startupFailedTitle': 'Ashore 启动失败',
        'saveSessionTip': '保存下载任务',
        'restartAria2Tip': '重新启动 aria2，运行中的任务会短暂刷新',
        'newDownloadTip': '新建下载任务',
        'resumeAllTip': '恢复所有暂停的任务',
        'pauseAllTip': '暂停所有下载中的任务',
        'downloadSpeed': '下载速度',
        'globalDownloadSpeed': '全局实时下载速度',
        'uploadSpeed': '上传速度',
        'globalUploadSpeed': '全局 BT / Magnet 上传速度',
        'unavailable': '不可用',
        'retrying': '已断开，正在重试',
        'stopped': '已停止',
        'unknown': '未知',
        'downloadComplete': '下载完成',
        'downloadFailed': '下载失败',
        'trackerApplyDeferred': 'Tracker 已保存，将在 aria2 下次启动时生效：{error}',
        'localConfigFallback': 'aria2 未连接，设置页显示本地配置：{error}',
        'migrationTitle': '更新默认下载目录',
        'migrationQuestion': '检测到旧版默认下载目录：\n{oldPath}\n\n系统当前提供的下载目录是：\n{newPath}\n\n是否切换？\n只有旧版默认值会触发此提示，用户自定义目录不会被覆盖。',
        'migrationApplyDeferred': '目录已保存，运行中的 aria2 未能立即应用：{error}',
        'updateFailedTitle': '更新失败',
        'configWriteFailed': '无法写入 aria2 配置文件。',
        'addTaskFailedTitle': '添加任务失败',
        'existingFileTitle': '目标文件已存在',
        'existingFileQuestion': '目标位置已存在文件：\n{path}',
        'existingFileInfo': '没有发现可用于续传的 .aria2 进度文件，无法确认现有文件是否完整。',
        'redownloadOverwrite': '重新下载并覆盖',
        'keepAndSaveAs': '保留原文件并另存',
        'aboutDescription': '基于 Python 与 PyQt6 的 aria2 桌面下载管理器',
        'aboutAuthor': '作者',
        'aboutProject': '项目地址',
        'aboutPythonVersion': 'Python 版本',
        'aboutAshoreVersion': 'Ashore 版本',
        'aboutAria2Version': 'aria2 版本',
        'restartAria2FailedTitle': '无法重启 aria2',
        'copiedToClipboard': '已复制到剪贴板',
        'deleteSuccess': '删除成功',
        'manualRestartRequired': '{error} 配置已保存，请手动重启 aria2 后生效。',
        'configSavedRuntimeFailed': '配置已保存，但运行中 aria2 未能应用设置：{error}',
        'aria2ConfigSaveFailed': 'aria2 配置未能保存，请检查配置目录权限。',
        'saved': '保存成功',
        'saveFailed': '保存失败',

        'pauseTask': '暂停任务', 'startTask': '继续任务', 'openFile': '打开文件',
        'openFolder': '打开目录', 'retryTask': '重试', 'copyLink': '复制下载链接',
        'moreActions': '更多操作', 'removeFromList': '从列表移除',
        'deleteTaskFiles': '删除任务和文件…', 'deleteTaskTitle': '删除任务和文件',
        'deleteTaskQuestion': '删除任务和已下载文件？',
        'deleteTaskInfo': '此操作会删除 aria2 为该任务列出的下载文件。',
        'cancel': '取消', 'deleteFiles': '删除文件',
        'waitingStatus': '等待中', 'pausedStatus': '已暂停',
        'completedStatus': '已完成', 'errorStatus': '错误',

        'aria2Settings': 'Aria2 设置', 'ashoreSettings': 'Ashore 设置',
        'basicSettings': '基本设置', 'defaultDownloadDir': '默认下载目录:',
        'chooseDirectory': '选择目录', 'maxConcurrentDownloads': '同时最大下载数:',
        'maxConnectionsServer': '同一服务器连接数:', 'speedLimits': '限速设置:',
        'uploadLimit': '上传限速', 'downloadLimit': '下载限速', 'unlimited': '不限速',
        'rpcPort': 'RPC 监听端口:', 'httpPolling': 'HTTP 轮询:',
        'websocketNotifications': 'WebSocket 通知:', 'aria2Version': 'aria2 版本:',
        'externalRpc': '允许外部访问 RPC:', 'yes': '是', 'no': '否',
        'rpcToken': 'RPC 授权令牌:', 'reveal': '显示', 'conceal': '隐藏',
        'copy': '复制', 'copied': '已复制', 'btSettings': 'BT 设置',
        'updateTracker': '更新 Tracker', 'trackerUpdating': '更新中…',
        'trackerFailed': '更新失败',
        'neverUpdated': '尚未更新',
        'trackerUpToDate': 'BT Tracker 已是最新',
        'trackerUpdatingStatus': '正在更新 BT Tracker',
        'trackerUpdateFailedKeeping': 'BT Tracker 更新失败，继续使用现有列表',
        'trackerSaveFailedKeeping': 'BT Tracker 保存失败，继续使用现有列表',
        'trackerUpdateComplete': 'BT Tracker 更新完成',
        'trackerConfigWriteFailed': '无法写入配置目录', 'autoTracker': '启动时自动更新 Tracker:',
        'autoTrackerHint': '仅在上次成功更新超过 24 小时后执行',
        'quitWithAria2': 'aria2 随程序关闭:', 'refreshInterval': '界面刷新间隔:',
        'milliseconds': '毫秒', 'allowRpcPortChange': '允许修改 RPC 接口:',
        'interfaceLanguage': '界面语言:', 'trayIconStyle': '托盘图标样式:',
        'showAria2Status': '显示主界面 aria2 状态:',
        'colorful': '彩色', 'gray': '灰色', 'themeMode': '明暗主题:',
        'followSystem': '跟随系统', 'light': '浅色', 'dark': '深色',
        'accentColor': '主题颜色:', 'chooseColor': '选择颜色',
        'saveSettings': '保存设置', 'waitingCheck': '等待检测',
        'connected': '已连接', 'disconnected': '未连接', 'connecting': '连接中',
        'manualConfiguration': '手动配置',
        'trackerSources': 'Tracker 来源:',
        'addTrackerSource': '添加自定义来源',
        'invalidTrackerSource': '请输入有效的 HTTP/HTTPS Tracker 列表地址。',
        'duplicateTrackerSource': '这个 Tracker 来源已经存在。',
        'noTrackerSources': '请至少启用一个 Tracker 来源。',
        'trackerSummary': '当前列表 {count} 条；已启用 {sources} 个来源。列表数量不代表连接有效。',
        'trackerUpdated': '从 {sources} 个来源合并获取 {count} 条 Tracker，已保存。',
        'trackerUpdateFailed': '更新失败：{error}；保留原列表。',
        'trackerManager': '管理 Tracker', 'manageTrackers': '管理 Tracker…',
        'trackerManagement': 'Tracker 管理',
        'trackerUrl': 'URL', 'trackerHealth': '状态', 'trackerLatency': '延迟',
        'trackerHealthy': '可用', 'trackerUnavailable': '不可用',
        'notChecked': '未检测', 'checkTrackers': '检测全部',
        'checkingTrackers': '检测中…', 'addTracker': '添加',
        'removeTracker': '移除', 'apply': '应用',
        'trackerManagerSummary': '当前 {count} 个 Tracker，尚未进行本次健康检测。',
        'trackerHealthSummary': '共 {count} 个 · {healthy} 可用 · {failed} 不可用',
        'trackerOverview': 'Tracker 管理:', 'lastTrackerUpdate': '最近更新 {time}',

        'newDownloadTitle': '新建下载', 'downloadInputLabel': 'URL / Magnet / Torrent',
        'downloadInputPlaceholder': '粘贴 HTTP / HTTPS / FTP / Magnet 地址，或拖入 .torrent 文件\n多个任务每行一个',
        'openTorrent': '打开 Torrent…', 'validTaskCount': '已识别 {count} 个有效任务',
        'invalidInputCount': '{count} 个输入无效', 'invalidInputPrompt': '请修正无效输入：{items}',
        'saveTo': '保存到', 'advancedOptions': '高级选项',
        'fileName': '文件名:', 'fileNameHint': '仅单个普通 HTTP/FTP 文件可用',
        'leaveDefault': '留空使用默认值', 'userAgentHint': '留空使用全局 User-Agent',
        'headersHint': '每行一个，例如：\nAccept-Language: zh-CN\nX-Token: value',
        'cookieHint': '例如：session=abc; theme=dark',
        'checksumHint': '例如：sha-256=0123abcd…',
        'advancedDownloadHint': '高级选项只应用到 HTTP / HTTPS / FTP 请求；Magnet 和本地 Torrent 不会收到无关参数。',
        'startDownload': '开始下载', 'invalidHeader': '无效 HTTP Header：{line}',
        'checksumFormat': 'Checksum 应使用“算法=摘要”格式。',
        'chooseDownloadDir': '请选择下载目录。',
        'recoveryIntro': 'Ashore 使用 aria2 作为下载引擎。当前环境未通过启动检查，因此主界面不会启动。',
        'recoveryReason': '环境状态：{reason}',
        'recoveryIssueMissing': '未检测到 aria2c。',
        'recoveryIssueRpc': 'aria2 已存在，但 RPC 未能正常启动。',
        'recoveryIssueStartup': 'aria2 启动检查失败。',
        'recoverySystem': '当前系统：{system}',
        'recoveryInstallCommand': '推荐的 aria2 安装命令',
        'copyCommand': '复制命令', 'recheckEnvironment': '重新检测',
        'quitAshore': '退出 Ashore',
    },
    'zh_TW': {
        'new': '新增下載', 'saveSession': '儲存工作階段', 'restart': '重新啟動 Aria2',
        'quit': '結束程式', 'startAll': '全部開始', 'pauseAll': '全部暫停',
        'show': '顯示視窗', 'hide': '關閉視窗', 'about': '關於 Ashore',
        'showMain': '顯示主視窗', 'trayQuit': '結束', 'exiting': '正在結束…',
        'downloading': '下載中', 'downloaded': '已完成', 'settings': '設定',
        'more': '更多',
        'startupLoadingConfig': '正在讀取設定',
        'startupCheckingInstance': '正在檢查執行中的實例',
        'startupCheckingAria2': '正在檢查 aria2',
        'startupAria2Connected': 'aria2 已連線',
        'startupPreparingWindow': '正在準備主介面',
        'startupSyncingDownloads': '正在同步下載任務',
        'startupShowingWindow': '正在顯示主介面',
        'startupRecheckingAria2': '正在重新檢查 aria2',
        'startupFailedTitle': 'Ashore 啟動失敗',
        'saveSessionTip': '儲存下載任務',
        'restartAria2Tip': '重新啟動 aria2，執行中的任務會短暫重新整理',
        'newDownloadTip': '新增下載任務',
        'resumeAllTip': '繼續所有暫停的任務',
        'pauseAllTip': '暫停所有下載中的任務',
        'downloadSpeed': '下載速度',
        'globalDownloadSpeed': '全域即時下載速度',
        'uploadSpeed': '上傳速度',
        'globalUploadSpeed': '全域 BT / Magnet 上傳速度',
        'unavailable': '不可用',
        'retrying': '已中斷，正在重試',
        'stopped': '已停止',
        'unknown': '未知',
        'downloadComplete': '下載完成',
        'downloadFailed': '下載失敗',
        'trackerApplyDeferred': 'Tracker 已儲存，將在 aria2 下次啟動時生效：{error}',
        'localConfigFallback': 'aria2 未連線，設定頁顯示本機設定：{error}',
        'migrationTitle': '更新預設下載目錄',
        'migrationQuestion': '偵測到舊版預設下載目錄：\n{oldPath}\n\n系統目前提供的下載目錄是：\n{newPath}\n\n是否切換？\n只有舊版預設值會觸發此提示，使用者自訂目錄不會被覆寫。',
        'migrationApplyDeferred': '目錄已儲存，執行中的 aria2 未能立即套用：{error}',
        'updateFailedTitle': '更新失敗',
        'configWriteFailed': '無法寫入 aria2 設定檔。',
        'addTaskFailedTitle': '新增任務失敗',
        'existingFileTitle': '目標檔案已存在',
        'existingFileQuestion': '目標位置已存在檔案：\n{path}',
        'existingFileInfo': '找不到可用於續傳的 .aria2 進度檔，無法確認現有檔案是否完整。',
        'redownloadOverwrite': '重新下載並覆寫',
        'keepAndSaveAs': '保留原檔並另存',
        'aboutDescription': '基於 Python 與 PyQt6 的 aria2 桌面下載管理器',
        'aboutAuthor': '作者',
        'aboutProject': '專案位址',
        'aboutPythonVersion': 'Python 版本',
        'aboutAshoreVersion': 'Ashore 版本',
        'aboutAria2Version': 'aria2 版本',
        'restartAria2FailedTitle': '無法重新啟動 aria2',
        'copiedToClipboard': '已複製到剪貼簿',
        'deleteSuccess': '刪除成功',
        'manualRestartRequired': '{error} 設定已儲存，請手動重新啟動 aria2 後生效。',
        'configSavedRuntimeFailed': '設定已儲存，但執行中的 aria2 未能套用設定：{error}',
        'aria2ConfigSaveFailed': 'aria2 設定未能儲存，請檢查設定目錄權限。',
        'saved': '儲存成功',
        'saveFailed': '儲存失敗',

        'pauseTask': '暫停任務', 'startTask': '繼續任務', 'openFile': '開啟檔案',
        'openFolder': '開啟資料夾', 'retryTask': '重試', 'copyLink': '複製下載連結',
        'moreActions': '更多操作', 'removeFromList': '從清單移除',
        'deleteTaskFiles': '刪除任務和檔案…', 'deleteTaskTitle': '刪除任務和檔案',
        'deleteTaskQuestion': '刪除任務和已下載檔案？',
        'deleteTaskInfo': '此操作會刪除 aria2 為該任務列出的下載檔案。',
        'cancel': '取消', 'deleteFiles': '刪除檔案',
        'waitingStatus': '等待中', 'pausedStatus': '已暫停',
        'completedStatus': '已完成', 'errorStatus': '錯誤',

        'aria2Settings': 'Aria2 設定', 'ashoreSettings': 'Ashore 設定',
        'basicSettings': '基本設定', 'defaultDownloadDir': '預設下載目錄:',
        'chooseDirectory': '選擇目錄', 'maxConcurrentDownloads': '同時最大下載數:',
        'maxConnectionsServer': '同一伺服器連線數:', 'speedLimits': '限速設定:',
        'uploadLimit': '上傳限速', 'downloadLimit': '下載限速', 'unlimited': '不限速',
        'rpcPort': 'RPC 監聽連接埠:', 'httpPolling': 'HTTP 輪詢:',
        'websocketNotifications': 'WebSocket 通知:', 'aria2Version': 'aria2 版本:',
        'externalRpc': '允許外部存取 RPC:', 'yes': '是', 'no': '否',
        'rpcToken': 'RPC 授權權杖:', 'reveal': '顯示', 'conceal': '隱藏',
        'copy': '複製', 'copied': '已複製', 'btSettings': 'BT 設定',
        'updateTracker': '更新 Tracker', 'trackerUpdating': '更新中…',
        'trackerFailed': '更新失敗',
        'neverUpdated': '尚未更新',
        'trackerUpToDate': 'BT Tracker 已是最新',
        'trackerUpdatingStatus': '正在更新 BT Tracker',
        'trackerUpdateFailedKeeping': 'BT Tracker 更新失敗，繼續使用現有清單',
        'trackerSaveFailedKeeping': 'BT Tracker 儲存失敗，繼續使用現有清單',
        'trackerUpdateComplete': 'BT Tracker 更新完成',
        'trackerConfigWriteFailed': '無法寫入設定目錄', 'autoTracker': '啟動時自動更新 Tracker:',
        'autoTrackerHint': '僅在上次成功更新超過 24 小時後執行',
        'quitWithAria2': 'aria2 隨程式關閉:', 'refreshInterval': '介面更新間隔:',
        'milliseconds': '毫秒', 'allowRpcPortChange': '允許修改 RPC 介面:',
        'interfaceLanguage': '介面語言:', 'trayIconStyle': '托盤圖示樣式:',
        'showAria2Status': '顯示主介面 aria2 狀態:',
        'colorful': '彩色', 'gray': '灰色', 'themeMode': '明暗主題:',
        'followSystem': '跟隨系統', 'light': '淺色', 'dark': '深色',
        'accentColor': '主題顏色:', 'chooseColor': '選擇顏色',
        'saveSettings': '儲存設定', 'waitingCheck': '等待檢測',
        'connected': '已連線', 'disconnected': '未連線', 'connecting': '連線中',
        'manualConfiguration': '手動設定',
        'trackerSources': 'Tracker 來源:',
        'addTrackerSource': '新增自訂來源',
        'invalidTrackerSource': '請輸入有效的 HTTP/HTTPS Tracker 清單網址。',
        'duplicateTrackerSource': '這個 Tracker 來源已存在。',
        'noTrackerSources': '請至少啟用一個 Tracker 來源。',
        'trackerSummary': '目前清單 {count} 條；已啟用 {sources} 個來源。清單數量不代表連線有效。',
        'trackerUpdated': '從 {sources} 個來源合併取得 {count} 條 Tracker，已儲存。',
        'trackerUpdateFailed': '更新失敗：{error}；保留原清單。',
        'trackerManager': '管理 Tracker', 'manageTrackers': '管理 Tracker…',
        'trackerManagement': 'Tracker 管理',
        'trackerUrl': 'URL', 'trackerHealth': '狀態', 'trackerLatency': '延遲',
        'trackerHealthy': '可用', 'trackerUnavailable': '不可用',
        'notChecked': '未檢測', 'checkTrackers': '全部檢測',
        'checkingTrackers': '檢測中…', 'addTracker': '新增',
        'removeTracker': '移除', 'apply': '套用',
        'trackerManagerSummary': '目前 {count} 個 Tracker，尚未進行本次健康檢測。',
        'trackerHealthSummary': '共 {count} 個 · {healthy} 可用 · {failed} 不可用',
        'trackerOverview': 'Tracker 管理:', 'lastTrackerUpdate': '最近更新 {time}',

        'newDownloadTitle': '新增下載', 'downloadInputLabel': 'URL / Magnet / Torrent',
        'downloadInputPlaceholder': '貼上 HTTP / HTTPS / FTP / Magnet 位址，或拖入 .torrent 檔案\n多個任務每行一個',
        'openTorrent': '開啟 Torrent…', 'validTaskCount': '已識別 {count} 個有效任務',
        'invalidInputCount': '{count} 個輸入無效', 'invalidInputPrompt': '請修正無效輸入：{items}',
        'saveTo': '儲存到', 'advancedOptions': '進階選項',
        'fileName': '檔名:', 'fileNameHint': '僅單一普通 HTTP/FTP 檔案可用',
        'leaveDefault': '留空使用預設值', 'userAgentHint': '留空使用全域 User-Agent',
        'headersHint': '每行一個，例如：\nAccept-Language: zh-TW\nX-Token: value',
        'cookieHint': '例如：session=abc; theme=dark',
        'checksumHint': '例如：sha-256=0123abcd…',
        'advancedDownloadHint': '進階選項只套用到 HTTP / HTTPS / FTP 請求；Magnet 和本機 Torrent 不會收到無關參數。',
        'startDownload': '開始下載', 'invalidHeader': '無效 HTTP Header：{line}',
        'checksumFormat': 'Checksum 應使用「演算法=摘要」格式。',
        'chooseDownloadDir': '請選擇下載目錄。',
        'recoveryIntro': 'Ashore 使用 aria2 作為下載引擎。目前環境未通過啟動檢查，因此主介面不會啟動。',
        'recoveryReason': '環境狀態：{reason}',
        'recoveryIssueMissing': '未檢測到 aria2c。',
        'recoveryIssueRpc': 'aria2 已存在，但 RPC 未能正常啟動。',
        'recoveryIssueStartup': 'aria2 啟動檢查失敗。',
        'recoverySystem': '目前系統：{system}',
        'recoveryInstallCommand': '建議的 aria2 安裝命令',
        'copyCommand': '複製命令', 'recheckEnvironment': '重新檢測',
        'quitAshore': '結束 Ashore',
    },
    'en': {
        'new': 'New Download', 'saveSession': 'Save Session', 'restart': 'Restart Aria2',
        'quit': 'Quit Ashore', 'startAll': 'Start All', 'pauseAll': 'Pause All',
        'show': 'Show Window', 'hide': 'Hide Window', 'about': 'About Ashore',
        'showMain': 'Show Main Window', 'trayQuit': 'Quit', 'exiting': 'Exiting…',
        'downloading': 'Downloading', 'downloaded': 'Completed', 'settings': 'Settings',
        'more': 'More',
        'startupLoadingConfig': 'Loading configuration',
        'startupCheckingInstance': 'Checking running instance',
        'startupCheckingAria2': 'Checking aria2',
        'startupAria2Connected': 'aria2 connected',
        'startupPreparingWindow': 'Preparing main window',
        'startupSyncingDownloads': 'Synchronizing downloads',
        'startupShowingWindow': 'Showing main window',
        'startupRecheckingAria2': 'Rechecking aria2',
        'startupFailedTitle': 'Ashore startup failed',
        'saveSessionTip': 'Save the current download session',
        'restartAria2Tip': 'Restart aria2; running tasks will refresh briefly',
        'newDownloadTip': 'Create a new download',
        'resumeAllTip': 'Resume all paused downloads',
        'pauseAllTip': 'Pause all active downloads',
        'downloadSpeed': 'Download speed',
        'globalDownloadSpeed': 'Global real-time download speed',
        'uploadSpeed': 'Upload speed',
        'globalUploadSpeed': 'Global BT / Magnet upload speed',
        'unavailable': 'Unavailable',
        'retrying': 'Disconnected, retrying',
        'stopped': 'Stopped',
        'unknown': 'Unknown',
        'downloadComplete': 'Download complete',
        'downloadFailed': 'Download failed',
        'trackerApplyDeferred': 'Trackers were saved and will take effect the next time aria2 starts: {error}',
        'localConfigFallback': 'aria2 is not connected; showing local settings: {error}',
        'migrationTitle': 'Update default download directory',
        'migrationQuestion': 'An older default download directory was detected:\n{oldPath}\n\nThe system now provides:\n{newPath}\n\nSwitch to the new directory?\nThis prompt only applies to the old default; custom directories are never overwritten.',
        'migrationApplyDeferred': 'The directory was saved, but the running aria2 could not apply it immediately: {error}',
        'updateFailedTitle': 'Update failed',
        'configWriteFailed': 'Could not write the aria2 configuration file.',
        'addTaskFailedTitle': 'Could not add download',
        'existingFileTitle': 'Target file already exists',
        'existingFileQuestion': 'A file already exists at:\n{path}',
        'existingFileInfo': 'No usable .aria2 progress file was found, so Ashore cannot confirm whether the existing file is complete.',
        'redownloadOverwrite': 'Redownload and replace',
        'keepAndSaveAs': 'Keep existing and save as new',
        'aboutDescription': 'A desktop aria2 download manager built with Python and PyQt6',
        'aboutAuthor': 'Author',
        'aboutProject': 'Project',
        'aboutPythonVersion': 'Python version',
        'aboutAshoreVersion': 'Ashore version',
        'aboutAria2Version': 'aria2 version',
        'restartAria2FailedTitle': 'Could not restart aria2',
        'copiedToClipboard': 'Copied to clipboard',
        'deleteSuccess': 'Deleted',
        'manualRestartRequired': '{error} Settings were saved; restart aria2 manually to apply them.',
        'configSavedRuntimeFailed': 'Settings were saved, but the running aria2 could not apply them: {error}',
        'aria2ConfigSaveFailed': 'Could not save the aria2 configuration. Check the configuration-directory permissions.',
        'saved': 'Saved',
        'saveFailed': 'Save failed',

        'pauseTask': 'Pause task', 'startTask': 'Resume task', 'openFile': 'Open file',
        'openFolder': 'Open folder', 'retryTask': 'Retry', 'copyLink': 'Copy download link',
        'moreActions': 'More actions', 'removeFromList': 'Remove from list',
        'deleteTaskFiles': 'Delete task and files…', 'deleteTaskTitle': 'Delete task and files',
        'deleteTaskQuestion': 'Delete the task and downloaded files?',
        'deleteTaskInfo': 'This removes the files that aria2 lists for this task.',
        'cancel': 'Cancel', 'deleteFiles': 'Delete files',
        'waitingStatus': 'Waiting', 'pausedStatus': 'Paused',
        'completedStatus': 'Completed', 'errorStatus': 'Error',

        'aria2Settings': 'Aria2 Settings', 'ashoreSettings': 'Ashore Settings',
        'basicSettings': 'Basic Settings', 'defaultDownloadDir': 'Default download directory:',
        'chooseDirectory': 'Choose Folder', 'maxConcurrentDownloads': 'Maximum concurrent downloads:',
        'maxConnectionsServer': 'Connections per server:', 'speedLimits': 'Speed limits:',
        'uploadLimit': 'Upload limit', 'downloadLimit': 'Download limit', 'unlimited': 'Unlimited',
        'rpcPort': 'RPC listening port:', 'httpPolling': 'HTTP polling:',
        'websocketNotifications': 'WebSocket notifications:', 'aria2Version': 'aria2 version:',
        'externalRpc': 'Allow external RPC access:', 'yes': 'Yes', 'no': 'No',
        'rpcToken': 'RPC access token:', 'reveal': 'Show', 'conceal': 'Hide',
        'copy': 'Copy', 'copied': 'Copied', 'btSettings': 'BT Settings',
        'updateTracker': 'Update Trackers', 'trackerUpdating': 'Updating…',
        'trackerFailed': 'Update failed',
        'neverUpdated': 'Never updated',
        'trackerUpToDate': 'BT Trackers are up to date',
        'trackerUpdatingStatus': 'Updating BT Trackers',
        'trackerUpdateFailedKeeping': 'BT Tracker update failed; keeping the existing list',
        'trackerSaveFailedKeeping': 'Could not save BT Trackers; keeping the existing list',
        'trackerUpdateComplete': 'BT Trackers updated',
        'trackerConfigWriteFailed': 'Could not write the configuration directory', 'autoTracker': 'Update trackers at startup:',
        'autoTrackerHint': 'Only when the last successful update was more than 24 hours ago',
        'quitWithAria2': 'Stop aria2 when Ashore exits:', 'refreshInterval': 'UI refresh interval:',
        'milliseconds': 'ms', 'allowRpcPortChange': 'Allow changing the RPC port:',
        'interfaceLanguage': 'Interface language:', 'trayIconStyle': 'Tray icon style:',
        'showAria2Status': 'Show aria2 status in main window:',
        'colorful': 'Color', 'gray': 'Gray', 'themeMode': 'Theme:',
        'followSystem': 'Follow system', 'light': 'Light', 'dark': 'Dark',
        'accentColor': 'Accent color:', 'chooseColor': 'Choose Color',
        'saveSettings': 'Save Settings', 'waitingCheck': 'Waiting for check',
        'connected': 'Connected', 'disconnected': 'Disconnected', 'connecting': 'Connecting',
        'manualConfiguration': 'Manual configuration',
        'trackerSources': 'Tracker sources:',
        'addTrackerSource': 'Add Custom Source',
        'invalidTrackerSource': 'Enter a valid HTTP/HTTPS tracker-list URL.',
        'duplicateTrackerSource': 'This Tracker source already exists.',
        'noTrackerSources': 'Enable at least one Tracker source.',
        'trackerSummary': '{count} trackers; {sources} source(s) enabled. Count does not imply connectivity.',
        'trackerUpdated': 'Merged {count} trackers from {sources} source(s). Saved.',
        'trackerUpdateFailed': 'Update failed: {error}. Existing list kept.',
        'trackerManager': 'Manage Trackers', 'manageTrackers': 'Manage Trackers…',
        'trackerManagement': 'Tracker Management',
        'trackerUrl': 'URL', 'trackerHealth': 'Status', 'trackerLatency': 'Latency',
        'trackerHealthy': 'Reachable', 'trackerUnavailable': 'Unavailable',
        'notChecked': 'Not checked', 'checkTrackers': 'Check All',
        'checkingTrackers': 'Checking…', 'addTracker': 'Add',
        'removeTracker': 'Remove', 'apply': 'Apply',
        'trackerManagerSummary': '{count} trackers; no health check has been run in this session.',
        'trackerHealthSummary': '{count} total · {healthy} reachable · {failed} unavailable',
        'trackerOverview': 'Tracker management:', 'lastTrackerUpdate': 'Last update {time}',

        'newDownloadTitle': 'New Download', 'downloadInputLabel': 'URL / Magnet / Torrent',
        'downloadInputPlaceholder': 'Paste HTTP / HTTPS / FTP / Magnet addresses, or drop .torrent files\nOne task per line',
        'openTorrent': 'Open Torrent…', 'validTaskCount': '{count} valid task(s) detected',
        'invalidInputCount': '{count} invalid input(s)', 'invalidInputPrompt': 'Fix invalid input: {items}',
        'saveTo': 'Save to', 'advancedOptions': 'Advanced',
        'fileName': 'File name:', 'fileNameHint': 'Available for one regular HTTP/FTP file only',
        'leaveDefault': 'Leave blank to use the default', 'userAgentHint': 'Leave blank to use the global User-Agent',
        'headersHint': 'One per line, for example:\nAccept-Language: en-AU\nX-Token: value',
        'cookieHint': 'For example: session=abc; theme=dark',
        'checksumHint': 'For example: sha-256=0123abcd…',
        'advancedDownloadHint': 'Advanced options apply only to HTTP / HTTPS / FTP requests; Magnet and local Torrent tasks do not receive unrelated options.',
        'startDownload': 'Download', 'invalidHeader': 'Invalid HTTP header: {line}',
        'checksumFormat': 'Checksum must use the “algorithm=digest” format.',
        'chooseDownloadDir': 'Choose a download directory.',
        'recoveryIntro': 'Ashore uses aria2 as its download engine. The environment check did not pass, so the main window has not been started.',
        'recoveryReason': 'Environment status: {reason}',
        'recoveryIssueMissing': 'aria2c was not found.',
        'recoveryIssueRpc': 'aria2 is installed, but its RPC service did not become ready.',
        'recoveryIssueStartup': 'The aria2 startup check failed.',
        'recoverySystem': 'Current system: {system}',
        'recoveryInstallCommand': 'Recommended aria2 installation command',
        'copyCommand': 'Copy Command', 'recheckEnvironment': 'Recheck',
        'quitAshore': 'Quit Ashore',
    },
}

def translate(language, key):
    languageText = TEXT.get(language, TEXT['en'])
    return languageText.get(key, TEXT['en'].get(key, key))
