"""Centralized runtime translations for Ashore."""

LANGUAGES = {
    'zh_CN': '简体中文',
    'zh_TW': '繁體中文',
    'en': 'English',
}

TEXT = {
    'zh_CN': {
        'new': '新建下载', 'saveSession': '保存会话', 'restart': '重启 Aria2',
        'quit': '退出程序', 'startAll': '开始全部', 'pauseAll': '暂停全部',
        'show': '显示窗口', 'hide': '关闭窗口', 'about': '关于 Ashore',
        'showMain': '显示主窗口', 'trayQuit': '退出', 'exiting': '正在退出…',
        'downloading': '下载中', 'downloaded': '已完成', 'settings': '设置',
        'more': '更多',

        'pauseTask': '暂停任务', 'startTask': '继续任务', 'openFile': '打开文件',
        'openFolder': '打开目录', 'retryTask': '重试', 'copyLink': '复制下载链接',
        'moreActions': '更多操作', 'removeFromList': '从列表移除',
        'deleteTaskFiles': '删除任务和文件…', 'deleteTaskTitle': '删除任务和文件',
        'deleteTaskQuestion': '删除任务和已下载文件？',
        'deleteTaskInfo': '此操作会删除 aria2 为该任务列出的下载文件。',
        'cancel': '取消', 'deleteFiles': '删除文件',
        'waitingStatus': '等待中', 'pausedStatus': '已暂停',
        'completedStatus': '已完成', 'errorStatus': '错误',

        'aria2Settings': 'Aria2 设置', 'ashoreSettings': 'Ashore 设置',
        'basicSettings': '基本设置', 'defaultDownloadDir': '默认下载目录:',
        'chooseDirectory': '选择目录', 'maxConcurrentDownloads': '同时最大下载数:',
        'maxConnectionsServer': '同一服务器连接数:', 'speedLimits': '限速设置:',
        'uploadLimit': '上传限速', 'downloadLimit': '下载限速', 'unlimited': '不限速',
        'rpcPort': 'RPC 监听端口:', 'httpPolling': 'HTTP 轮询:',
        'websocketNotifications': 'WebSocket 通知:', 'aria2Version': 'aria2 版本:',
        'externalRpc': '允许外部访问 RPC:', 'yes': '是', 'no': '否',
        'rpcToken': 'RPC 授权令牌:', 'reveal': '显示', 'conceal': '隐藏',
        'copy': '复制', 'copied': '已复制', 'btSettings': 'BT 设置',
        'updateTracker': '更新 Tracker', 'trackerUpdating': '更新中…',
        'trackerFailed': '更新失败', 'autoTracker': '启动时自动更新 Tracker:',
        'autoTrackerHint': '仅在上次成功更新超过 24 小时后执行',
        'quitWithAria2': 'aria2 随程序关闭:', 'refreshInterval': '界面刷新间隔:',
        'milliseconds': '毫秒', 'allowRpcPortChange': '允许修改 RPC 接口:',
        'interfaceLanguage': '界面语言:', 'trayIconStyle': '托盘图标样式:',
        'showAria2Status': '显示主界面 aria2 状态:',
        'colorful': '彩色', 'gray': '灰色', 'themeMode': '明暗主题:',
        'followSystem': '跟随系统', 'light': '浅色', 'dark': '深色',
        'accentColor': '主题颜色:', 'chooseColor': '选择颜色',
        'saveSettings': '保存设置', 'waitingCheck': '等待检测',
        'connected': '已连接', 'disconnected': '未连接', 'connecting': '连接中',
        'manualConfiguration': '手动配置',
        'trackerSummary': '当前列表 {count} 条；来源：{source}。列表数量不代表连接有效。',
        'trackerUpdated': '获取 {count} 条；来源：{source}。已保存。',
        'trackerUpdateFailed': '更新失败：{error}；保留原列表。',

        'newDownloadTitle': '新建下载', 'downloadInputLabel': 'URL / Magnet / Torrent',
        'downloadInputPlaceholder': '粘贴 HTTP / HTTPS / FTP / Magnet 地址，或拖入 .torrent 文件\n多个任务每行一个',
        'openTorrent': '打开 Torrent…', 'validTaskCount': '已识别 {count} 个有效任务',
        'invalidInputCount': '{count} 个输入无效', 'invalidInputPrompt': '请修正无效输入：{items}',
        'saveTo': '保存到', 'advancedOptions': '高级选项',
        'fileName': '文件名:', 'fileNameHint': '仅单个普通 HTTP/FTP 文件可用',
        'leaveDefault': '留空使用默认值', 'userAgentHint': '留空使用全局 User-Agent',
        'headersHint': '每行一个，例如：\nAccept-Language: zh-CN\nX-Token: value',
        'cookieHint': '例如：session=abc; theme=dark',
        'checksumHint': '例如：sha-256=0123abcd…',
        'advancedDownloadHint': '高级选项只应用到 HTTP / HTTPS / FTP 请求；Magnet 和本地 Torrent 不会收到无关参数。',
        'startDownload': '开始下载', 'invalidHeader': '无效 HTTP Header：{line}',
        'checksumFormat': 'Checksum 应使用“算法=摘要”格式。',
        'chooseDownloadDir': '请选择下载目录。',
    },
    'zh_TW': {
        'new': '新增下載', 'saveSession': '儲存工作階段', 'restart': '重新啟動 Aria2',
        'quit': '結束程式', 'startAll': '全部開始', 'pauseAll': '全部暫停',
        'show': '顯示視窗', 'hide': '關閉視窗', 'about': '關於 Ashore',
        'showMain': '顯示主視窗', 'trayQuit': '結束', 'exiting': '正在結束…',
        'downloading': '下載中', 'downloaded': '已完成', 'settings': '設定',
        'more': '更多',

        'pauseTask': '暫停任務', 'startTask': '繼續任務', 'openFile': '開啟檔案',
        'openFolder': '開啟資料夾', 'retryTask': '重試', 'copyLink': '複製下載連結',
        'moreActions': '更多操作', 'removeFromList': '從清單移除',
        'deleteTaskFiles': '刪除任務和檔案…', 'deleteTaskTitle': '刪除任務和檔案',
        'deleteTaskQuestion': '刪除任務和已下載檔案？',
        'deleteTaskInfo': '此操作會刪除 aria2 為該任務列出的下載檔案。',
        'cancel': '取消', 'deleteFiles': '刪除檔案',
        'waitingStatus': '等待中', 'pausedStatus': '已暫停',
        'completedStatus': '已完成', 'errorStatus': '錯誤',

        'aria2Settings': 'Aria2 設定', 'ashoreSettings': 'Ashore 設定',
        'basicSettings': '基本設定', 'defaultDownloadDir': '預設下載目錄:',
        'chooseDirectory': '選擇目錄', 'maxConcurrentDownloads': '同時最大下載數:',
        'maxConnectionsServer': '同一伺服器連線數:', 'speedLimits': '限速設定:',
        'uploadLimit': '上傳限速', 'downloadLimit': '下載限速', 'unlimited': '不限速',
        'rpcPort': 'RPC 監聽連接埠:', 'httpPolling': 'HTTP 輪詢:',
        'websocketNotifications': 'WebSocket 通知:', 'aria2Version': 'aria2 版本:',
        'externalRpc': '允許外部存取 RPC:', 'yes': '是', 'no': '否',
        'rpcToken': 'RPC 授權權杖:', 'reveal': '顯示', 'conceal': '隱藏',
        'copy': '複製', 'copied': '已複製', 'btSettings': 'BT 設定',
        'updateTracker': '更新 Tracker', 'trackerUpdating': '更新中…',
        'trackerFailed': '更新失敗', 'autoTracker': '啟動時自動更新 Tracker:',
        'autoTrackerHint': '僅在上次成功更新超過 24 小時後執行',
        'quitWithAria2': 'aria2 隨程式關閉:', 'refreshInterval': '介面更新間隔:',
        'milliseconds': '毫秒', 'allowRpcPortChange': '允許修改 RPC 介面:',
        'interfaceLanguage': '介面語言:', 'trayIconStyle': '托盤圖示樣式:',
        'showAria2Status': '顯示主介面 aria2 狀態:',
        'colorful': '彩色', 'gray': '灰色', 'themeMode': '明暗主題:',
        'followSystem': '跟隨系統', 'light': '淺色', 'dark': '深色',
        'accentColor': '主題顏色:', 'chooseColor': '選擇顏色',
        'saveSettings': '儲存設定', 'waitingCheck': '等待檢測',
        'connected': '已連線', 'disconnected': '未連線', 'connecting': '連線中',
        'manualConfiguration': '手動設定',
        'trackerSummary': '目前清單 {count} 條；來源：{source}。清單數量不代表連線有效。',
        'trackerUpdated': '取得 {count} 條；來源：{source}。已儲存。',
        'trackerUpdateFailed': '更新失敗：{error}；保留原清單。',

        'newDownloadTitle': '新增下載', 'downloadInputLabel': 'URL / Magnet / Torrent',
        'downloadInputPlaceholder': '貼上 HTTP / HTTPS / FTP / Magnet 位址，或拖入 .torrent 檔案\n多個任務每行一個',
        'openTorrent': '開啟 Torrent…', 'validTaskCount': '已識別 {count} 個有效任務',
        'invalidInputCount': '{count} 個輸入無效', 'invalidInputPrompt': '請修正無效輸入：{items}',
        'saveTo': '儲存到', 'advancedOptions': '進階選項',
        'fileName': '檔名:', 'fileNameHint': '僅單一普通 HTTP/FTP 檔案可用',
        'leaveDefault': '留空使用預設值', 'userAgentHint': '留空使用全域 User-Agent',
        'headersHint': '每行一個，例如：\nAccept-Language: zh-TW\nX-Token: value',
        'cookieHint': '例如：session=abc; theme=dark',
        'checksumHint': '例如：sha-256=0123abcd…',
        'advancedDownloadHint': '進階選項只套用到 HTTP / HTTPS / FTP 請求；Magnet 和本機 Torrent 不會收到無關參數。',
        'startDownload': '開始下載', 'invalidHeader': '無效 HTTP Header：{line}',
        'checksumFormat': 'Checksum 應使用「演算法=摘要」格式。',
        'chooseDownloadDir': '請選擇下載目錄。',
    },
    'en': {
        'new': 'New Download', 'saveSession': 'Save Session', 'restart': 'Restart Aria2',
        'quit': 'Quit Ashore', 'startAll': 'Start All', 'pauseAll': 'Pause All',
        'show': 'Show Window', 'hide': 'Hide Window', 'about': 'About Ashore',
        'showMain': 'Show Main Window', 'trayQuit': 'Quit', 'exiting': 'Exiting…',
        'downloading': 'Downloading', 'downloaded': 'Completed', 'settings': 'Settings',
        'more': 'More',

        'pauseTask': 'Pause task', 'startTask': 'Resume task', 'openFile': 'Open file',
        'openFolder': 'Open folder', 'retryTask': 'Retry', 'copyLink': 'Copy download link',
        'moreActions': 'More actions', 'removeFromList': 'Remove from list',
        'deleteTaskFiles': 'Delete task and files…', 'deleteTaskTitle': 'Delete task and files',
        'deleteTaskQuestion': 'Delete the task and downloaded files?',
        'deleteTaskInfo': 'This removes the files that aria2 lists for this task.',
        'cancel': 'Cancel', 'deleteFiles': 'Delete files',
        'waitingStatus': 'Waiting', 'pausedStatus': 'Paused',
        'completedStatus': 'Completed', 'errorStatus': 'Error',

        'aria2Settings': 'Aria2 Settings', 'ashoreSettings': 'Ashore Settings',
        'basicSettings': 'Basic Settings', 'defaultDownloadDir': 'Default download directory:',
        'chooseDirectory': 'Choose Folder', 'maxConcurrentDownloads': 'Maximum concurrent downloads:',
        'maxConnectionsServer': 'Connections per server:', 'speedLimits': 'Speed limits:',
        'uploadLimit': 'Upload limit', 'downloadLimit': 'Download limit', 'unlimited': 'Unlimited',
        'rpcPort': 'RPC listening port:', 'httpPolling': 'HTTP polling:',
        'websocketNotifications': 'WebSocket notifications:', 'aria2Version': 'aria2 version:',
        'externalRpc': 'Allow external RPC access:', 'yes': 'Yes', 'no': 'No',
        'rpcToken': 'RPC access token:', 'reveal': 'Show', 'conceal': 'Hide',
        'copy': 'Copy', 'copied': 'Copied', 'btSettings': 'BT Settings',
        'updateTracker': 'Update Trackers', 'trackerUpdating': 'Updating…',
        'trackerFailed': 'Update failed', 'autoTracker': 'Update trackers at startup:',
        'autoTrackerHint': 'Only when the last successful update was more than 24 hours ago',
        'quitWithAria2': 'Stop aria2 when Ashore exits:', 'refreshInterval': 'UI refresh interval:',
        'milliseconds': 'ms', 'allowRpcPortChange': 'Allow changing the RPC port:',
        'interfaceLanguage': 'Interface language:', 'trayIconStyle': 'Tray icon style:',
        'showAria2Status': 'Show aria2 status in main window:',
        'colorful': 'Color', 'gray': 'Gray', 'themeMode': 'Theme:',
        'followSystem': 'Follow system', 'light': 'Light', 'dark': 'Dark',
        'accentColor': 'Accent color:', 'chooseColor': 'Choose Color',
        'saveSettings': 'Save Settings', 'waitingCheck': 'Waiting for check',
        'connected': 'Connected', 'disconnected': 'Disconnected', 'connecting': 'Connecting',
        'manualConfiguration': 'Manual configuration',
        'trackerSummary': '{count} trackers; source: {source}. Count does not imply connectivity.',
        'trackerUpdated': 'Loaded {count} trackers from {source}. Saved.',
        'trackerUpdateFailed': 'Update failed: {error}. Existing list kept.',

        'newDownloadTitle': 'New Download', 'downloadInputLabel': 'URL / Magnet / Torrent',
        'downloadInputPlaceholder': 'Paste HTTP / HTTPS / FTP / Magnet addresses, or drop .torrent files\nOne task per line',
        'openTorrent': 'Open Torrent…', 'validTaskCount': '{count} valid task(s) detected',
        'invalidInputCount': '{count} invalid input(s)', 'invalidInputPrompt': 'Fix invalid input: {items}',
        'saveTo': 'Save to', 'advancedOptions': 'Advanced',
        'fileName': 'File name:', 'fileNameHint': 'Available for one regular HTTP/FTP file only',
        'leaveDefault': 'Leave blank to use the default', 'userAgentHint': 'Leave blank to use the global User-Agent',
        'headersHint': 'One per line, for example:\nAccept-Language: en-AU\nX-Token: value',
        'cookieHint': 'For example: session=abc; theme=dark',
        'checksumHint': 'For example: sha-256=0123abcd…',
        'advancedDownloadHint': 'Advanced options apply only to HTTP / HTTPS / FTP requests; Magnet and local Torrent tasks do not receive unrelated options.',
        'startDownload': 'Download', 'invalidHeader': 'Invalid HTTP header: {line}',
        'checksumFormat': 'Checksum must use the “algorithm=digest” format.',
        'chooseDownloadDir': 'Choose a download directory.',
    },
}

def translate(language, key):
    languageText = TEXT.get(language, TEXT['zh_CN'])
    return languageText.get(key, TEXT['zh_CN'].get(key, key))
